// This file was automatically generated by the T4 Template
// Do not make changes directly to this file - edit the template instead
// 
// The following connection settings were used to generate this file
// 
//     Connection String Name: `ConnectionString`
//     Provider:               `System.Data.SqlClient`
//     Schema:                 `public`
//     Include Views:          `true`
//
//     Last Generated:         `1/25/2026 3:35:10 PM`

namespace LifeApp.SDK.Models
{
    [NPoco.TableName("AspNetRoleClaims")]
    [NPoco.PrimaryKey("RoleClaimId")]
    public partial class AspNetRoleClaim
    {
        public string RoleClaimId { get; set; }
        public string RoleId { get; set; }
        public string ClaimType { get; set; }
        public string ClaimValue { get; set; }
    } 
    [NPoco.TableName("AspNetRoles")]
    [NPoco.PrimaryKey("RoleId")]
    public partial class AspNetRole
    {
        public string RoleId { get; set; }
        public string Name { get; set; }
        public string NormalizedName { get; set; }
        public string ConcurrencyStamp { get; set; }
    } 
    [NPoco.TableName("AspNetUserClaims")]
    [NPoco.PrimaryKey("UserClaimId")]
    public partial class AspNetUserClaim
    {
        public string UserClaimId { get; set; }
        public string UserId { get; set; }
        public string ClaimType { get; set; }
        public string ClaimValue { get; set; }
    } 
    [NPoco.TableName("AspNetUserLogins")]
    [NPoco.PrimaryKey("LoginProvider, ProviderKey, UserId")]
    public partial class AspNetUserLogin
    {
        public string LoginProvider { get; set; }
        public string ProviderKey { get; set; }
        public string ProviderDisplayName { get; set; }
        public string UserId { get; set; }
    } 
    [NPoco.TableName("AspNetUserRoles")]
    [NPoco.PrimaryKey("RoleId, UserId")]
    public partial class AspNetUserRole
    {
        public string UserId { get; set; }
        public string RoleId { get; set; }
    } 
    [NPoco.TableName("AspNetUsers")]
    [NPoco.PrimaryKey("Id")]
    public partial class AspNetUser
    {
        public string Id { get; set; }
        public string UserName { get; set; }
        public string NormalizedUserName { get; set; }
        public string Email { get; set; }
        public string NormalizedEmail { get; set; }
        public bool EmailConfirmed { get; set; }
        public string PasswordHash { get; set; }
        public string SecurityStamp { get; set; }
        public string ConcurrencyStamp { get; set; }
        public string PhoneNumber { get; set; }
        public bool PhoneNumberConfirmed { get; set; }
        public bool TwoFactorEnabled { get; set; }
        public DateTimeOffset? LockoutEnd { get; set; }
        public bool LockoutEnabled { get; set; }
        public int AccessFailedCount { get; set; }
    } 
    [NPoco.TableName("OrderAllocations")]
    [NPoco.PrimaryKey("OrderAllocationId", AutoIncrement = true)]
    public partial class OrderAllocation
    {
        public long OrderAllocationId { get; set; }
        public long SeasonId { get; set; }
        public long TurnId { get; set; }
        public long TeamId { get; set; }
        public long TerritoryId { get; set; }
        public string UserId { get; set; }
    } 
    [NPoco.TableName("Teams")]
    [NPoco.PrimaryKey("TeamId", AutoIncrement = true)]
    public partial class Team
    {
        public long TeamId { get; set; }
        public string TeamName { get; set; }
        public string TeamPrimaryColor { get; set; }
        public string TeamSecondaryColor { get; set; }
    } 
    [NPoco.TableName("Territories")]
    [NPoco.PrimaryKey("TerritoryId", AutoIncrement = true)]
    public partial class Territory
    {
        public long TerritoryId { get; set; }
        public string TerritoryName { get; set; }
    } 
    [NPoco.TableName("UserOrders")]
    [NPoco.PrimaryKey("UserOrderId", AutoIncrement = true)]
    public partial class UserOrder
    {
        public long UserOrderId { get; set; }
        public string UserId { get; set; }
        public long SeasonId { get; set; }
        public long TurnId { get; set; }
        public long TeamId { get; set; }
        public long TerritoryId { get; set; }
        public int Starpower { get; set; }
    } 
}

