







// This file was automatically generated by the PetaPoco T4 Template
// Do not make changes directly to this file - edit the template instead
//
// The following connection settings were used to generate this file
//
//     Connection String Name: `ConnectionString`
//     Provider:               `System.Data.SqlClient`
//     Connection String:      `Server=db39041.public.databaseasp.net; Database=db39041; User Id=db39041; password=**zapped**;`
//     Schema:                 ``
//     Include Views:          `True`
//
//     Last Generated:         `1/26/2026 6:50:21 PM`

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace LifeApp.SDK.Models
{

    public partial class AspNetRole
    {
		public string Id { get; set; }
		public string Name { get; set; }
		public string NormalizedName { get; set; }
		public string ConcurrencyStamp { get; set; }
	}
    public partial class AspNetRoleClaim
    {
		public int Id { get; set; }
		public string RoleId { get; set; }
		public string ClaimType { get; set; }
		public string ClaimValue { get; set; }
	}
    public partial class AspNetUser
    {
		public string Id { get; set; }
		public string UserName { get; set; }
		public string NormalizedUserName { get; set; }
		public string Email { get; set; }
		public string NormalizedEmail { get; set; }
		public bool EmailConfirmed { get; set; }
		public string PasswordHash { get; set; }
		public string SecurityStamp { get; set; }
		public string ConcurrencyStamp { get; set; }
		public string PhoneNumber { get; set; }
		public bool PhoneNumberConfirmed { get; set; }
		public bool TwoFactorEnabled { get; set; }
		public DateTimeOffset? LockoutEnd { get; set; }
		public bool LockoutEnabled { get; set; }
		public int AccessFailedCount { get; set; }
	}
    public partial class AspNetUserClaim
    {
		public int Id { get; set; }
		public string UserId { get; set; }
		public string ClaimType { get; set; }
		public string ClaimValue { get; set; }
	}
    public partial class AspNetUserRole
    {
		public string UserId { get; set; }
		public string RoleId { get; set; }
	}
    public partial class AspNetUserToken
    {
		public string UserId { get; set; }
		public string LoginProvider { get; set; }
		public string Name { get; set; }
		public string Value { get; set; }
	}
    public partial class WishList
    {
		public long WishListId { get; set; }
		public string WishListName { get; set; }
		public string WishListItemLink { get; set; }
		public DateTime CreateDate { get; set; }
		public string CreateById { get; set; }
		public DateTime? UpdateDate { get; set; }
		public string UpdateById { get; set; }
		public bool IsEnabled { get; set; }
	}
    public partial class WishListPriority
    {
		public int WishListPriorityId { get; set; }
		public string WishListPriorityDesc { get; set; }
	}











    public enum WishListPrioritiesEnum
    {
			INeedThisASAP = 1,
			INeedThisWithinTheNext6Months = 2,
			INeedThisWithin1Year = 3,
			IWantItAndWouldBuyItMyself = 4,
			IWantItAndWouldNotBuyItMyself = 5
	}




}

